Set-StrictMode -Version 3

function BuildDataloaderProcessConfXml{
    [CmdletBinding(DefaultParameterSetName = 'authentication_sfdx_oauth')]
    param (
        [Parameter(Mandatory, Position=0)]
        [string]$ProcessName,

        [Parameter(Mandatory, Position=1)]
        $ConfigOverrideMap
    )

    # --------------------------------------- Build the process-conf.xml
	[string[]]$ProcessConfXml = @()   # empty array to collect all XML strings
	$ProcessConfXml += '<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">'
	$ProcessConfXml += '<beans>'
	$ProcessConfXml += "<bean id=""$ProcessName"" class=""com.salesforce.dataloader.process.ProcessRunner"">"
	$ProcessConfXml += '<description>Auto-generated by SfDataloader module</description>'    
    $ProcessConfXml += "<property name=""name"" value=""$ProcessName"" />"
    $ProcessConfXml += '<property name="configOverrideMap">'
    $ProcessConfXml += '<map>'

#	foreach($key in $ConfigOverrideMap.keys) {
    foreach($item in $ConfigOverrideMap.getEnumerator() | Sort-Object Name) {
            $key = $item.Name
            $ProcessConfXml += "<entry key=""$key"" value=""$($ConfigOverrideMap[$key])"" />" 
	}

    $ProcessConfXml += '</map>'
    $ProcessConfXml += '</property>'
    $ProcessConfXml += '</bean>'
    $ProcessConfXml += '</beans>'

    return $ProcessConfXml
}
